### PR TITLE
Add spacer to Navigation node.

### PR DESCRIPTION
**Pull request by px01tv**
Default false.

Allows me to dynamically put spacers on the sidebar.

Eg:

```php
{% if node.spacer %}
<hr>
{% endif %}
```

### CODE REVIEW

**Comment by gdude2002** [comment]
Would this mean "put a spacer before this item" or "put a spacer after this item"?

**Comment by px01tv** [comment]
After

**Comment by gdude2002** [comment]
What will happen if that's specified for the last child of a node? will the divider be inside or outside of the current navigation level?

I think we need a better solution than tagging nodes that already exist. Perhaps there's a way to have a separate spacer item?

**Comment by px01tv** [comment]
I don't know kotlin much. So you would have to code it.

**Comment by px01tv** [comment]
But for now, its a good temporary option.

**Comment by gdude2002** [comment]
I think this is going to require a more specific approach, making use of polymorphism. For that reason, I'm going to close this PR and start work on that.

**Pull request closed without merging**
